
package Vistas;


import Modelo.dasistencia;
import Controladores.nasistencia;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;



public class Frm_Asistencias extends javax.swing.JFrame {

    
    public Frm_Asistencias() {
        initComponents();
        
        
          this.setLocationRelativeTo(null);
    mostrar ("");
        
          btnguardar.setEnabled(true);
            btneliminar.setEnabled(false);
             btnmodificar.setEnabled(false);
        
         mostrarFechaEnTxtFecha();
        
        
    }
  private void mostrarFechaEnTxtFecha() {
       
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

       
        LocalDate currentDate = LocalDate.now();

       
        String formattedDate = currentDate.format(formatter);

       
      txtfechaasistencia.setText(formattedDate);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtnivel = new javax.swing.JTextField();
        txtgrado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtfechaasistencia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbojustificado = new javax.swing.JComboBox<>();
        cbotarde = new javax.swing.JComboBox<>();
        cbofalta = new javax.swing.JComboBox<>();
        jButton17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtcodestudiante = new javax.swing.JLabel();
        txtcodgrado = new javax.swing.JLabel();
        txtcodusuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asistencia");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 1010, 160));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/nuevo_1.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Grabar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 40));

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/modificcar_4.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 40));

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Delete.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, 40));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Exit.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 620, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, -1));

        jLabel4.setText("Tarde");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 60, 20));

        jLabel3.setText("Grado");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, 20));

        jLabel6.setText("Dni");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 70, 20));

        jLabel7.setText("Justificado");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 90, 20));

        txtapellidos.setEditable(false);
        jPanel2.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 210, -1));

        txtdni.setEditable(false);
        jPanel2.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 170, -1));

        txtnivel.setEditable(false);
        txtnivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnivelActionPerformed(evt);
            }
        });
        txtnivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnivelKeyTyped(evt);
            }
        });
        jPanel2.add(txtnivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 220, -1));

        txtgrado.setEditable(false);
        jPanel2.add(txtgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, -1));

        jLabel5.setText("Nivel");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 40, 20));

        jLabel9.setText("Nombres");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 80, 20));

        txtnombres.setEditable(false);
        jPanel2.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, -1));

        txtcodigo.setEditable(false);
        jPanel2.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 210, -1));

        txtfechaasistencia.setEditable(false);
        txtfechaasistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaasistenciaActionPerformed(evt);
            }
        });
        txtfechaasistencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechaasistenciaKeyTyped(evt);
            }
        });
        jPanel2.add(txtfechaasistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, -1));

        jLabel11.setText("Apellidos");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));

        jLabel12.setText("F-Asistencia");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        jLabel10.setText("Falto");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 100, 40));

        cbojustificado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", " " }));
        jPanel2.add(cbojustificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 220, -1));

        cbotarde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", " " }));
        jPanel2.add(cbotarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 220, -1));

        cbofalta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", " " }));
        jPanel2.add(cbofalta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 220, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Male.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 40, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 620, 180));

        jLabel1.setText("Estudiante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 80, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 540, -1));

        txtcodestudiante.setForeground(new java.awt.Color(204, 255, 255));
        txtcodestudiante.setText("jLabel13");
        jPanel1.add(txtcodestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        txtcodgrado.setForeground(new java.awt.Color(204, 255, 255));
        txtcodgrado.setText("jLabel14");
        jPanel1.add(txtcodgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        txtcodusuario.setForeground(new java.awt.Color(204, 255, 255));
        txtcodusuario.setText("1");
        jPanel1.add(txtcodusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 30, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked

        int fila =listado.rowAtPoint(evt.getPoint());

        txtcodigo.setText(listado.getValueAt(fila,0).toString());
        txtcodestudiante.setText(listado.getValueAt(fila,1).toString());
        txtdni.setText(listado.getValueAt(fila,2).toString());
        
        txtnombres.setText(listado.getValueAt(fila,3).toString());
        txtapellidos.setText(listado.getValueAt(fila,4).toString());
         txtcodgrado.setText(listado.getValueAt(fila,5).toString());
          txtgrado.setText(listado.getValueAt(fila,6).toString());
            txtnivel.setText(listado.getValueAt(fila,7).toString());
         cbotarde.setSelectedItem(listado.getValueAt(fila, 8).toString());
         cbofalta.setSelectedItem(listado.getValueAt(fila, 9).toString());
         
         cbojustificado.setSelectedItem(listado.getValueAt(fila, 10).toString());
         
             
         txtfechaasistencia.setText(listado.getValueAt(fila,11).toString());

       

        
        
        
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(true);
        btnmodificar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        JOptionPane.showMessageDialog(this, "Ingrese los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

         this.txtfechaasistencia.setText("");
        this.txtcodigo.setText("");
        this.txtapellidos.setText("");
        this.txtgrado.setText("");
        this.txtnivel.setText("");
     txtdni.setText("");
        jTextField1.setText("");
 this.txtgrado.setText("");
            
        mostrar ("");
        btnguardar.setEnabled(true);
        btneliminar.setEnabled(false);
        btnmodificar.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoActionPerformed
void mostrar (String buscar){
            
        
        try  {
        
            DefaultTableModel modelo;
            nasistencia f = new nasistencia();
            
            
      
            
            modelo = f.mostrar (buscar);
            
            
        
            
            listado.setModel(modelo);
            
             }catch(Exception e){
               
    JOptionPane.showMessageDialog(rootPane,e);
       
           }
           
      }


   
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        if(txtdni.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Seleccione el Estudiante","Aviso",JOptionPane.ERROR_MESSAGE);

        }

       
        
        else if (txtnivel.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Selecciona el Estudiante","Aviso",JOptionPane.ERROR_MESSAGE);

        }

      

        else  {

            dasistencia v = new  dasistencia();

            nasistencia f = new nasistencia ();

         

            v.setEstudiante(txtcodestudiante.getText());
               v.setGrado(txtcodgrado.getText());
     
                v.setTarde(cbotarde.getSelectedItem().toString());
                 v.setFalto(cbofalta.getSelectedItem().toString());
                  v.setJustificado(cbojustificado.getSelectedItem().toString());
                  
                            v.setF_asistencia(txtfechaasistencia.getText());
          
              v.setCod_usuario(txtcodusuario.getText());


            f.insertar(v);

            JOptionPane.showMessageDialog(this, "Asido Guardado los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

              mostrar ("");

            this.txtcodigo.setText("");
            
            this.txtfechaasistencia.setText("");
            
                     this.txtfechaasistencia.setText("");
            this.txtapellidos.setText("");
            this.txtgrado.setText("");
            this.txtnivel.setText("");
         txtdni.setText("");
            btnguardar.setEnabled(true);
            btneliminar.setEnabled(false);
            btnmodificar.setEnabled(false);
            this.txtnombres.setText("");
          
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed

        dasistencia v = new  dasistencia();

        nasistencia f = new nasistencia();

        v.setIdasistencia(Integer.parseInt(txtcodigo.getText()));

          
            v.setEstudiante(txtcodestudiante.getText());
               v.setGrado(txtcodgrado.getText());
     
                v.setTarde(cbotarde.getSelectedItem().toString());
                 v.setFalto(cbofalta.getSelectedItem().toString());
                  v.setJustificado(cbojustificado.getSelectedItem().toString());
                  
                            v.setF_asistencia(txtfechaasistencia.getText());
          
              v.setCod_usuario(txtcodusuario.getText());

           

          

        ///

        f.editar(v);

        JOptionPane.showMessageDialog(this, "Asido Modificado los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

          mostrar ("");
                 this.txtfechaasistencia.setText("");
  
            this.txtfechaasistencia.setText("");
        this.txtcodigo.setText("");
        this.txtapellidos.setText("");
        this.txtgrado.setText("");
        this.txtnivel.setText("");
txtdni.setText("");
        btnguardar.setEnabled(true);
        btneliminar.setEnabled(false);
        btnmodificar.setEnabled(false);
        this.txtnombres.setText("");
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        if (!txtcodigo.getText().equals("")){

            int con=  JOptionPane.showConfirmDialog(rootPane, "Asido Eliminado los Dato");

            if (con ==0 ){

             dasistencia v = new  dasistencia();

        nasistencia f = new nasistencia();


             v.setIdasistencia(Integer.parseInt(txtcodigo.getText()));

                f.eliminar(v);

             mostrar ("");

            this.txtfechaasistencia.setText("");
                this.txtcodigo.setText("");
                this.txtapellidos.setText("");
                this.txtgrado.setText("");
                this.txtnivel.setText("");
               txtdni.setText("");
                btnguardar.setEnabled(true);
                btneliminar.setEnabled(false);
                btnmodificar.setEnabled(false);
         this.txtfechaasistencia.setText("");
         
           this.txtnombres.setText("");
            this.txtfechaasistencia.setText("");
            
            }

        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtnivelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnivelKeyTyped

    

        // TODO add your handling code here:
    }//GEN-LAST:event_txtnivelKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        
        
      mostrar(jTextField1.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void txtfechaasistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaasistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaasistenciaActionPerformed

    private void txtfechaasistenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechaasistenciaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaasistenciaKeyTyped

    private void txtnivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnivelActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        Frm_Consulta_Estudiante_Matriculado X = new     Frm_Consulta_Estudiante_Matriculado();
        X.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Asistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Asistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Asistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Asistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Asistencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbofalta;
    private javax.swing.JComboBox<String> cbojustificado;
    private javax.swing.JComboBox<String> cbotarde;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable listado;
    public static javax.swing.JTextField txtapellidos;
    public static javax.swing.JLabel txtcodestudiante;
    public static javax.swing.JLabel txtcodgrado;
    private javax.swing.JTextField txtcodigo;
    public static javax.swing.JLabel txtcodusuario;
    public static javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtfechaasistencia;
    public static javax.swing.JTextField txtgrado;
    public static javax.swing.JTextField txtnivel;
    public static javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
