
package Vistas;
import Modelo.dgrado;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

import java.io.IOException;
import java.net.URISyntaxException;

import Controladores.ngrado;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Frm_Grado extends javax.swing.JFrame {

   
    public Frm_Grado() {
      initComponents();
        
        
          this.setLocationRelativeTo(null);
       mostrar ("");
        
          jButton2.setEnabled(true);
            jButton4.setEnabled(false);
             jButton5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtgrado = new javax.swing.JTextField();
        txtnivel = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtcoddocente = new javax.swing.JLabel();
        txtcodcurso = new javax.swing.JLabel();
        txtcodperiodo = new javax.swing.JLabel();
        txtcodmateria = new javax.swing.JLabel();
        btnIcono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grado");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 720, 180));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/nuevo_1.png"))); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Grabar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/modificcar_4.png"))); // NOI18N
        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Delete.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Exit.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 680, 70));

        jLabel1.setText("Grado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 480, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Codigo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Sesion");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 60, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Grado");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 30));
        jPanel2.add(txtgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 220, -1));

        txtnivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnivelActionPerformed(evt);
            }
        });
        txtnivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnivelKeyTyped(evt);
            }
        });
        jPanel2.add(txtnivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 220, -1));
        jPanel2.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nivel");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 40, 20));

        txtcodigo.setEditable(false);
        jPanel2.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 220, -1));

        txtcoddocente.setForeground(new java.awt.Color(153, 204, 255));
        txtcoddocente.setText("Padre");
        jPanel2.add(txtcoddocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 60, 20));

        txtcodcurso.setForeground(new java.awt.Color(153, 204, 255));
        txtcodcurso.setText("Padre");
        jPanel2.add(txtcodcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 60, 20));

        txtcodperiodo.setForeground(new java.awt.Color(153, 204, 255));
        txtcodperiodo.setText("Padre");
        jPanel2.add(txtcodperiodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 60, 20));

        txtcodmateria.setForeground(new java.awt.Color(153, 204, 255));
        txtcodmateria.setText("Padre");
        jPanel2.add(txtcodmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, 20));

        btnIcono.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX\\Downloads\\icono_info.png")); // NOI18N
        btnIcono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIcono)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked

        int fila =listado.rowAtPoint(evt.getPoint());

        txtcodigo.setText(listado.getValueAt(fila,0).toString());
        
        txtgrado.setText(listado.getValueAt(fila,1).toString());
                txtnivel.setText(listado.getValueAt(fila,2).toString());

        txtdescripcion.setText(listado.getValueAt(fila,3).toString());
      


       


        jButton2.setEnabled(false);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(this, "Ingrese los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

     
        this.txtcodigo.setText("");
       
        this.txtdescripcion.setText("");
        this.txtnivel.setText("");
        this.txtcodigo.setText("");
          jTextField1.setText("");
            this.txtcodmateria.setText("");
           
            this.txtcoddocente.setText("");
            this.txtcodcurso.setText("");
            this.txtdescripcion.setText("");
            this.txtnivel.setText("");
            this.txtcodperiodo.setText("");
            
            this.txtnivel.setText("");
            this.txtgrado.setText("");
        this.txtgrado.setText("");
      
        jTextField1.setText("");
        this.txtdescripcion.setText("");
        
        mostrar ("");
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
void mostrar (String buscar){
            
        
        try  {
        
            DefaultTableModel modelo;
            ngrado f = new ngrado();
            
            
      
            
            modelo = f.mostrar (buscar);
            
            
      
            
            listado.setModel(modelo);
            
             }catch(Exception e){
               
    JOptionPane.showMessageDialog(rootPane,e);
       
           }
           
      }
     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(txtgrado.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Seleccionar el Periodo","Aviso",JOptionPane.ERROR_MESSAGE);

        }

       

        else if (txtdescripcion.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Ingrese la Descripcion","Aviso",JOptionPane.ERROR_MESSAGE);

        }

        else  {

            dgrado  v = new  dgrado();

            ngrado f = new ngrado ();

            v.setNombre(txtgrado.getText());

            v.setNivel(txtnivel.getText());

            v.setDescripcion(txtdescripcion.getText());

           
          

            f.insertar(v);

            JOptionPane.showMessageDialog(this, "Asido Guardado los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

            mostrar ("");

            this.txtcodigo.setText("");
          jTextField1.setText("");
            this.txtcodmateria.setText("");
           
            this.txtcoddocente.setText("");
            this.txtcodcurso.setText("");
            this.txtdescripcion.setText("");
            this.txtnivel.setText("");
            this.txtcodperiodo.setText("");
            
            this.txtnivel.setText("");
            this.txtgrado.setText("");
            
            
            
            jButton2.setEnabled(true);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
          
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

     dgrado  v = new  dgrado();

            ngrado f = new ngrado ();

               v.setIdgrado(Integer.parseInt(txtcodigo.getText()));
                    
             v.setNombre(txtgrado.getText());

            v.setNivel(txtnivel.getText());

            v.setDescripcion(txtdescripcion.getText());





        ///

        f.editar(v);

        JOptionPane.showMessageDialog(this, "Asido Modificado los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

  mostrar ("");
       
        this.txtcodigo.setText("");
       
        this.txtdescripcion.setText("");
        this.txtnivel.setText("");
        this.txtgrado.setText("");
           jTextField1.setText("");
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (!txtcodigo.getText().equals("")){

            int con=  JOptionPane.showConfirmDialog(rootPane, "Asido Eliminado los Dato");

            if (con ==0 ){

                dgrado  v = new  dgrado();

            ngrado f = new ngrado ();

                 v.setIdgrado(Integer.parseInt(txtcodigo.getText()));

                f.eliminar(v);

                mostrar ("");
              
                this.txtcodigo.setText("");
              
                this.txtdescripcion.setText("");
                this.txtnivel.setText("");
                  jTextField1.setText("");
                this.txtgrado.setText("");
                jButton2.setEnabled(true);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
               

            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtnivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnivelActionPerformed

    private void txtnivelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnivelKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txtnivelKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

    mostrar (jTextField1.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btnIconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconoActionPerformed
             if (java.awt.Desktop.isDesktopSupported()) {

            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {

                try {
                    java.net.URI uri = new java.net.URI("http://127.0.0.1:5500/analisis_dise%C3%B1o.html");
                    desktop.browse(uri);
                } catch (IOException ex) {

                } catch (URISyntaxException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }  
        
        
        
    }//GEN-LAST:event_btnIconoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Grado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Grado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Grado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Grado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Grado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIcono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable listado;
    public static javax.swing.JLabel txtcodcurso;
    public static javax.swing.JLabel txtcoddocente;
    private javax.swing.JTextField txtcodigo;
    public static javax.swing.JLabel txtcodmateria;
    public static javax.swing.JLabel txtcodperiodo;
    private javax.swing.JTextField txtdescripcion;
    public static javax.swing.JTextField txtgrado;
    private javax.swing.JTextField txtnivel;
    // End of variables declaration//GEN-END:variables
}
