
package Vistas;
import Modelo.dalumno;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;



import Controladores.nalumno;
/**
 *
 * @author Usuario
 */
public class Frm_Estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Estudiante
     */
    public Frm_Estudiante() {
        initComponents();
        
        
          this.setLocationRelativeTo(null);
        mostrar("");
        
          jButton2.setEnabled(true);
            jButton4.setEnabled(false);
             jButton5.setEnabled(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtmadre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpadre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtlugar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        txtdocumento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudiante");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 860, 160));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/nuevo_1.png"))); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Grabar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/modificcar_4.png"))); // NOI18N
        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Delete.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Exit.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 620, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Codigo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, -1));

        jLabel4.setText("Padre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 60, 20));

        jLabel3.setText("Domicilio");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, 20));

        jLabel6.setText("Dni");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 70, 20));

        jLabel7.setText("Documentos");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 90, 20));
        jPanel2.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 210, -1));
        jPanel2.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 210, -1));

        txtmadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmadreActionPerformed(evt);
            }
        });
        txtmadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmadreKeyTyped(evt);
            }
        });
        jPanel2.add(txtmadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 220, -1));
        jPanel2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 220, -1));

        jLabel5.setText("Madre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 40, 20));

        txtpadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpadreActionPerformed(evt);
            }
        });
        txtpadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpadreKeyTyped(evt);
            }
        });
        jPanel2.add(txtpadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 220, -1));

        jLabel9.setText("Nombres");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 80, 20));
        jPanel2.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, -1));

        txtcodigo.setEditable(false);
        jPanel2.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 210, -1));

        txtlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlugarActionPerformed(evt);
            }
        });
        txtlugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlugarKeyTyped(evt);
            }
        });
        jPanel2.add(txtlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, -1));

        jLabel11.setText("Apellidos");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));

        jLabel12.setText("Lugar N");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        jLabel10.setText("F/Nacimiento");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 100, 40));

        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });
        txtfecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechaKeyTyped(evt);
            }
        });
        jPanel2.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 220, -1));

        txtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoActionPerformed(evt);
            }
        });
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });
        jPanel2.add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 620, 180));

        jLabel1.setText("Estudiante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 80, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 540, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked

        int fila =listado.rowAtPoint(evt.getPoint());

        txtcodigo.setText(listado.getValueAt(fila,0).toString());
        txtcedula.setText(listado.getValueAt(fila,1).toString());
        txtnombres.setText(listado.getValueAt(fila,2).toString());
        txtapellidos.setText(listado.getValueAt(fila,3).toString());
        txtfecha.setText(listado.getValueAt(fila,4).toString());

         txtlugar.setText(listado.getValueAt(fila,5).toString());

       

        txtmadre.setText(listado.getValueAt(fila,6).toString());

        txtpadre.setText(listado.getValueAt(fila,7).toString());

         txtdireccion.setText(listado.getValueAt(fila,8).toString());
        txtdocumento.setText(listado.getValueAt(fila,9).toString());
        
        
        jButton2.setEnabled(false);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(this, "Ingrese los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

         this.txtlugar.setText("");
        this.txtcodigo.setText("");
        this.txtapellidos.setText("");
        this.txtdireccion.setText("");
        this.txtmadre.setText("");
        txtpadre.setText("");
        this.txtcedula.setText("");
        this.txtnombres.setText("");
        this.txtfecha.setText("");
        jTextField1.setText("");
 this.txtdireccion.setText("");
            this.txtdocumento.setText("");
        mostrar ("");
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
void mostrar (String  buscardato){
            
        
        try  {
        
            DefaultTableModel modelo;
            nalumno f = new nalumno();
            
            
      
            
            modelo = f.mostrar (buscardato);
            
   
            
            listado.setModel(modelo);
            
             }catch(Exception e){
               
    JOptionPane.showMessageDialog(rootPane,e);
       
           }
           
      }


    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(txtcedula.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Ingrese la Cedula","Aviso",JOptionPane.ERROR_MESSAGE);

        }

        else if (txtnombres.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Ingrese los Nombres","Aviso",JOptionPane.ERROR_MESSAGE);

        }

        else if (txtapellidos.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Ingrese los Apellidos","Aviso",JOptionPane.ERROR_MESSAGE);

        }

        else if (txtmadre.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Ingrese Dato Madre","Aviso",JOptionPane.ERROR_MESSAGE);

        }

        else if (txtdireccion.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Ingrese la Ubicacion","Aviso",JOptionPane.ERROR_MESSAGE);

        }

        else  {

            dalumno  v = new  dalumno();

            nalumno f = new nalumno ();

            v.setcedula(txtcedula.getText());

            v.setnombres(txtnombres.getText());

            v.setapellidos(txtapellidos.getText());

            v.setfecha(txtfecha.getText());

              v.setlugar(txtlugar.getText());
              
                v.setmadre(txtmadre.getText());
                  v.setpadre(txtpadre.getText());
                  
            v.setdireccion(txtdireccion.getText());

           

            v.setdocumento(txtdocumento.getText());

            f.insertar(v);

            JOptionPane.showMessageDialog(this, "Asido Guardado los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

            mostrar ("");

            this.txtcodigo.setText("");
             this.txtdocumento.setText("");
            this.txtlugar.setText("");
            
                     this.txtlugar.setText("");
            this.txtapellidos.setText("");
            this.txtdireccion.setText("");
            this.txtmadre.setText("");
            this.txtcedula.setText("");
            this.txtpadre.setText("");
            jButton2.setEnabled(true);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            this.txtnombres.setText("");
            this.txtfecha.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        dalumno v = new  dalumno();

        nalumno f = new nalumno();

        v.setid_codigo(Integer.parseInt(txtcodigo.getText()));

           v.setcedula(txtcedula.getText());

            v.setnombres(txtnombres.getText());

            v.setapellidos(txtapellidos.getText());

            v.setfecha(txtfecha.getText());

              v.setlugar(txtlugar.getText());
              
                v.setmadre(txtmadre.getText());
                  v.setpadre(txtpadre.getText());
            v.setdireccion(txtdireccion.getText());

           

            v.setdocumento(txtdocumento.getText());

        ///

        f.editar(v);

        JOptionPane.showMessageDialog(this, "Asido Modificado los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

        mostrar ("");
                 this.txtlugar.setText("");
   this.txtdocumento.setText("");
            this.txtlugar.setText("");
        this.txtcodigo.setText("");
        this.txtapellidos.setText("");
        this.txtdireccion.setText("");
        this.txtmadre.setText("");
        this.txtcedula.setText("");
        this.txtpadre.setText("");
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        this.txtnombres.setText("");
        this.txtfecha.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (!txtcodigo.getText().equals("")){

            int con=  JOptionPane.showConfirmDialog(rootPane, "Asido Eliminado los Dato");

            if (con ==0 ){

                dalumno  v = new dalumno ();
                nalumno  f=  new nalumno ();

                v.setid_codigo(Integer.parseInt(txtcodigo.getText()));

                f.eliminar(v);

                mostrar ("");
   this.txtdocumento.setText("");
            this.txtlugar.setText("");
                this.txtcodigo.setText("");
                this.txtapellidos.setText("");
                this.txtdireccion.setText("");
                this.txtmadre.setText("");
                this.txtpadre.setText("");
                this.txtcedula.setText("");
                jButton2.setEnabled(true);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
         this.txtlugar.setText("");
         
           this.txtnombres.setText("");
            this.txtlugar.setText("");
              this.txtdocumento.setText("");
            this.txtfecha.setText("");
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtmadreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmadreKeyTyped

    

        // TODO add your handling code here:
    }//GEN-LAST:event_txtmadreKeyTyped

    private void txtpadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpadreActionPerformed

    private void txtpadreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpadreKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txtpadreKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        
         mostrar(jTextField1.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

      mostrar(jTextField1.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void txtlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlugarActionPerformed

    private void txtlugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlugarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlugarKeyTyped

    private void txtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoActionPerformed

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoKeyTyped

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void txtfechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaKeyTyped

    private void txtmadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmadreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable listado;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtlugar;
    private javax.swing.JTextField txtmadre;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtpadre;
    // End of variables declaration//GEN-END:variables
}
