
package Vistas;
import Controladores.ExportarExcel;
import Modelo.dmatricula;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;



import Controladores.nmatricula;
import java.io.IOException;

public class Frm_Matricula extends javax.swing.JFrame {

  
    public Frm_Matricula() {
        initComponents();
         this.setLocationRelativeTo(null);
 
        
          jButton2.setEnabled(true);
            jButton4.setEnabled(false);
             jButton5.setEnabled(false);
             
               mostrar ("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtcodestudiante = new javax.swing.JLabel();
        txtcodperiodo = new javax.swing.JLabel();
        txtcodrepresentante = new javax.swing.JLabel();
        txtcodcurso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcodgrado = new javax.swing.JLabel();
        txtcodgrados = new javax.swing.JLabel();
        txtcodestudiantes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtgrado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        txtnombres = new javax.swing.JTextField();
        cboperiodo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matricula del Estudiante");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 790, 160));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/nuevo_1.png"))); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Grabar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/modificcar_4.png"))); // NOI18N
        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Delete.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Exit.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 630, 80));

        jLabel1.setText("Estudiante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 80, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 540, -1));

        txtcodestudiante.setForeground(new java.awt.Color(204, 255, 255));
        txtcodestudiante.setText("jLabel3");
        jPanel1.add(txtcodestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        txtcodperiodo.setForeground(new java.awt.Color(204, 255, 255));
        txtcodperiodo.setText("jLabel4");
        jPanel1.add(txtcodperiodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        txtcodrepresentante.setForeground(new java.awt.Color(204, 255, 255));
        txtcodrepresentante.setText("jLabel5");
        jPanel1.add(txtcodrepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        txtcodcurso.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtcodcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));
        jPanel1.add(txtcodgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 50, 20));

        txtcodgrados.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtcodgrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, -1));

        txtcodestudiantes.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtcodestudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Matricula");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, -1));

        jLabel6.setText("Dni");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, 70, 30));

        jLabel7.setText("Estado");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 90, 20));

        txtdni.setEditable(false);
        txtdni.setBackground(new java.awt.Color(255, 255, 255));
        txtdni.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 170, -1));

        jLabel9.setText("Estudiante");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, 80, 30));

        txtapellidos.setEditable(false);
        txtapellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidos.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 110, -1));

        txtcodigo.setEditable(false);
        txtcodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtcodigo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 210, -1));

        txtgrado.setEditable(false);
        txtgrado.setBackground(new java.awt.Color(255, 255, 255));
        txtgrado.setForeground(new java.awt.Color(0, 0, 0));
        txtgrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgradoActionPerformed(evt);
            }
        });
        txtgrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgradoKeyTyped(evt);
            }
        });
        jPanel2.add(txtgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 180, -1));

        jLabel11.setText("Periodo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, 20));

        jLabel12.setText("Grado");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, 20));

        txtestado.setBackground(new java.awt.Color(255, 255, 255));
        txtestado.setForeground(new java.awt.Color(0, 0, 0));
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        txtestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtestadoKeyTyped(evt);
            }
        });
        jPanel2.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 220, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Male.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 40, -1));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/OK.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 40, -1));

        txtnombres.setEditable(false);
        txtnombres.setBackground(new java.awt.Color(255, 255, 255));
        txtnombres.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, -1));

        cboperiodo.setBackground(new java.awt.Color(255, 255, 255));
        cboperiodo.setForeground(new java.awt.Color(0, 0, 0));
        cboperiodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));
        jPanel2.add(cboperiodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 220, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 220));

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("EXEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadoMouseClicked

        int fila =listado.rowAtPoint(evt.getPoint());

        txtcodigo.setText(listado.getValueAt(fila,0).toString());
        
         txtcodestudiantes.setText(listado.getValueAt(fila,1).toString());
         
       txtdni.setText(listado.getValueAt(fila,2).toString());
        
        
           txtnombres.setText(listado.getValueAt(fila,3).toString());
        txtapellidos.setText(listado.getValueAt(fila,4).toString());
        
        
       
         
        
           txtgrado.setText(listado.getValueAt(fila,5).toString());
           
   
           
         cboperiodo.setSelectedItem(listado.getValueAt(fila, 7).toString());
         
         
              txtestado.setText(listado.getValueAt(fila,8).toString());


     
txtcodgrados.setText(listado.getValueAt(fila,9).toString());
      

        jButton2.setEnabled(false);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_listadoMouseClicked
void mostrar (String buscar){
            
        
        try  {
        
            DefaultTableModel modelo;
            nmatricula f = new nmatricula();
            
            
      
            
            modelo = f.mostrar (buscar);
            
            
    
            
            listado.setModel(modelo);
            
             }catch(Exception e){
               
    JOptionPane.showMessageDialog(rootPane,e);
       
           }
           
      }


    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(this, "Ingrese los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

        this.txtgrado.setText("");
        this.txtcodigo.setText("");
       
         this.txtdni.setText("");
  this.txtnombres.setText("");
   this.txtapellidos.setText("");
        this.txtdni.setText("");
        this.txtapellidos.setText("");
       
        jTextField1.setText("");

        this.txtestado.setText("");
        mostrar ("");
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(txtestado.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Ingrese Estado","Aviso",JOptionPane.ERROR_MESSAGE);

        }

        else if (txtapellidos.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Seleccionar Estudiante","Aviso",JOptionPane.ERROR_MESSAGE);

        }

       

        else if (txtgrado.getText().isEmpty())

        {
            JOptionPane.showMessageDialog(this, "Seleccionar Curso","Aviso",JOptionPane.ERROR_MESSAGE);

        }

     

        else  {

            dmatricula  v = new  dmatricula();

            nmatricula f = new nmatricula();

            v.setEstudiante(txtcodestudiantes.getText());

            v.setGrado(txtcodgrados.getText());
               
            v.setPeriodo(cboperiodo.getSelectedItem().toString());

            

            v.setEstado(txtestado.getText());

          


            f.insertar(v);

            JOptionPane.showMessageDialog(this, "Asido Guardado los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

            mostrar ("");

            this.txtcodigo.setText("");
            this.txtestado.setText("");
            this.txtgrado.setText("");
 this.txtdni.setText("");
  this.txtnombres.setText("");
   this.txtapellidos.setText("");
   
            this.txtcodcurso.setText("");
           
                        this.txtcodrepresentante.setText("");
                        
                              this.txtnombres.setText("");
                              this.txtapellidos.setText("");
                                   this.txtdni.setText("");
                                   
                              
            jButton2.setEnabled(true);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            this.txtapellidos.setText("");
      
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed



      

        dmatricula  v = new  dmatricula();

            nmatricula f = new nmatricula();

       v.setId(Integer.parseInt(txtcodigo.getText()));
              
           v.setEstudiante(txtcodestudiantes.getText());

            v.setGrado(txtcodgrados.getText());
               
   v.setPeriodo(cboperiodo.getSelectedItem().toString());

            

            v.setEstado(txtestado.getText());

        ///

        f.editar(v);

        JOptionPane.showMessageDialog(this, "Asido Modificado los Datos","Aviso",JOptionPane.INFORMATION_MESSAGE);

        mostrar ("");
        this.txtgrado.setText("");
        this.txtestado.setText("");
        this.txtgrado.setText("");
        this.txtcodigo.setText("");
       
          this.txtcodigo.setText("");
            this.txtestado.setText("");
            this.txtgrado.setText("");
 this.txtdni.setText("");
  this.txtnombres.setText("");
   this.txtapellidos.setText("");
            this.txtcodcurso.setText("");
          
                 this.txtcodperiodo.setText("");
            this.txtdni.setText("");
               
                        this.txtcodrepresentante.setText("");
                        
                              this.txtnombres.setText("");
                              this.txtapellidos.setText("");
                                   this.txtdni.setText("");
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        this.txtapellidos.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (!txtcodigo.getText().equals("")){

            int con=  JOptionPane.showConfirmDialog(rootPane, "Asido Eliminado los Dato");

            if (con ==0 ){

                       dmatricula  v = new  dmatricula();

                    nmatricula f = new nmatricula();

                v.setId(Integer.parseInt(txtcodigo.getText()));

                f.eliminar(v);

                mostrar ("");
                this.txtestado.setText("");
                this.txtgrado.setText("");
                this.txtcodigo.setText("");
               
               this.txtdni.setText("");
  this.txtnombres.setText("");
   this.txtapellidos.setText("");
                this.txtdni.setText("");
                jButton2.setEnabled(true);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
                this.txtgrado.setText("");
  this.txtcodigo.setText("");
            this.txtestado.setText("");
            this.txtgrado.setText("");

            this.txtcodcurso.setText("");

                 this.txtcodperiodo.setText("");
            this.txtdni.setText("");
                 
                        this.txtcodrepresentante.setText("");
                        
                              this.txtnombres.setText("");
                              this.txtapellidos.setText("");
                                   this.txtdni.setText("");
                this.txtapellidos.setText("");
                this.txtgrado.setText("");
      
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtgradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgradoActionPerformed

    private void txtgradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgradoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgradoKeyTyped

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtestadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtestadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
//
//        mostrardatos(jTextField1.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

       
        
          
           Frm_Consulta_Estudiante X = new     Frm_Consulta_Estudiante();
        X.setVisible(true);

        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed




          
           Frm_Consulta_Grado X = new     Frm_Consulta_Grado();
        X.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped


mostrar(jTextField1.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(listado);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Matricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboperiodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable listado;
    public static javax.swing.JTextField txtapellidos;
    public static javax.swing.JLabel txtcodcurso;
    public static javax.swing.JLabel txtcodestudiante;
    public static javax.swing.JLabel txtcodestudiantes;
    private javax.swing.JLabel txtcodgrado;
    public static javax.swing.JLabel txtcodgrados;
    private javax.swing.JTextField txtcodigo;
    public static javax.swing.JLabel txtcodperiodo;
    public static javax.swing.JLabel txtcodrepresentante;
    public static javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtestado;
    public static javax.swing.JTextField txtgrado;
    public static javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
